"""Local-mode release routing for the control panel: nginx's weighted upstream.

The panel runs in a container without a Docker socket, and nginx OSS has no runtime API, so the hand-over point is
the shared `nginx-routing` volume (compose.dev.yaml mounts it at NGINX_ROUTING_DIR):

- read-back: the header line of routing.conf, the file nginx includes (`# Generated by render-routing.sh 90 10 0 ...`),
  exactly what `apply-routing.sh --sync` (make route-show / route-check) reads;
- apply: `requests/request` = "<id> <w100> <w110> <w120>"; nginx/routing-watch.sh in the nginx container renders it
  with the same render-routing.sh as `make canary-*`, runs `nginx -t` (restoring the previous file on failure),
  reloads, and answers in `requests/result`.

Only three integers cross the volume. Apply, rollback memory and the demo:routing publish are WeightedRouting's,
shared with the ALB backend of the hybrid stack.
"""
from __future__ import annotations

import os
import re
import socket
import time
import uuid
from pathlib import Path
from typing import Callable

from .routing import TG_KEYS, RoutingError, WeightedRouting, fmt_weights, validate_weights

HEADER = re.compile(r"^# Generated by render-routing\.sh (\d+) (\d+) (\d+) ")
ANSWER_TIMEOUT_S = 15.0


def release_running(host: str) -> bool:
    """Docker's embedded DNS knows a compose service only while its container runs; nginx needs exactly that."""
    try:
        socket.getaddrinfo(host, 8080)
        return True
    except socket.gaierror:
        return False


class NginxRouting(WeightedRouting):
    where, label, kind = "nginx upstream", "nginx weights", "nginx"
    card_text = ("Changes the weighted upstream of the local nginx (the routing.conf that <code>make canary-*</code> "
                 "writes), then reads it back.")

    def __init__(self, routing_dir: str, redis_client, resolve: Callable[[str], bool] = release_running,
                 sleep: Callable[[float], None] = time.sleep, clock: Callable[[], float] = time.monotonic,
                 timeout_s: float = ANSWER_TIMEOUT_S, new_id: Callable[[], str] = lambda: uuid.uuid4().hex):
        self.dir = Path(routing_dir)
        self.conf, self.requests = self.dir / "routing.conf", self.dir / "requests"
        self._redis, self._resolve, self._sleep, self._clock = redis_client, resolve, sleep, clock
        self._timeout, self._new_id = timeout_s, new_id
        self.target = str(self.conf)

    def live(self) -> tuple[int, int, int]:
        try:
            with self.conf.open() as f:
                first = f.readline()
        except OSError as exc:
            raise RoutingError(f"could not read {self.conf} (nginx-routing volume, NGINX_ROUTING_DIR): {exc}") from exc
        m = HEADER.match(first)
        if not m:
            raise RoutingError(f"cannot read the weights from the routing.conf header {first.strip()!r}")
        return validate_weights([int(x) for x in m.groups()])

    def _modify(self, weights, progress: Callable[[str], None]) -> None:
        # Same rule as apply-routing.sh: a release that is not running cannot take traffic (nginx would not resolve it).
        for rel, w in zip(TG_KEYS, weights):
            if w > 0 and not self._resolve(f"inventory-api-{rel}"):
                raise RoutingError(f"weight {w} for inventory-api-{rel} but that container is not running. Releases "
                                   "1.1.0/1.2.0 belong to the layer 'releases': run make layer-on L=releases first.")
        rid = self._new_id()
        request, tmp = self.requests / "request", self.requests / f".request-{rid}.tmp"
        try:
            tmp.write_text(f"{rid} {fmt_weights(weights)}\n")
            os.replace(tmp, request)
        except OSError as exc:
            raise RoutingError(f"could not write the routing request into {self.requests}: {exc}") from exc
        progress("Waiting for nginx to test and reload the routing")
        deadline = self._clock() + self._timeout
        while True:
            answer = self._answer(rid)
            if answer is not None:
                status, _, detail = answer.partition(" ")
                if status == "ok":
                    return
                raise RoutingError(f"nginx refused the routing {fmt_weights(weights)}: {detail or answer}")
            if self._clock() >= deadline:
                try:
                    request.unlink()  # not picked up yet: withdraw it, so nothing changes after this failure
                    withdrawn = "the request was withdrawn, routing unchanged"
                except FileNotFoundError:
                    withdrawn = "nginx picked the request up late: press Refresh weights to see the live routing"
                raise RoutingError(f"nginx did not answer the routing request within {self._timeout:g} s ({withdrawn}). "
                                   "Is routing-watch.sh running in the nginx container? See: docker compose logs nginx")
            self._sleep(0.25)

    def _answer(self, rid: str) -> str | None:
        try:
            line = (self.requests / "result").read_text().strip()
        except FileNotFoundError:
            return None
        except OSError as exc:
            raise RoutingError(f"could not read {self.requests / 'result'}: {exc}") from exc
        got, _, rest = line.partition(" ")
        return rest if got == rid else None
