#!/usr/bin/env bash
# Creates <repo>/.env.secrets with random role passwords if it does not exist, and appends any password that is missing
# from an existing file. Existing values are never changed or printed (rotating means deleting the file AND the postgres volume).
set -euo pipefail

overlay="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
root="$(cd "$overlay/.." && pwd)"
if [ -n "${ENV_DIR:-}" ]; then
  ENV_DIR="$ENV_DIR"
elif [ -f "$overlay/.env" ]; then
  ENV_DIR="$overlay"
elif [ -f "$root/.env" ]; then
  ENV_DIR="$root"
else
  ENV_DIR="$overlay"
fi
target="$ENV_DIR/.env.secrets"
names=(PG_SUPERUSER_PASSWORD PG_DEBEZIUM_PASSWORD PG_WRITER_PASSWORD PG_DATADOG_PASSWORD PG_PROCUREMENT_PASSWORD CONTROL_PASSWORD)

command -v openssl >/dev/null || { echo "gen-secrets: openssl is required to generate passwords" >&2; exit 1; }

umask 077
created=0
if [ ! -e "$target" ]; then
  echo "# Generated by overlay/compose/scripts/gen-secrets.sh. Secrets: keep untracked (gitignored)." > "$target"
  created=1
fi

added=()
for name in "${names[@]}"; do
  if ! grep -q "^${name}=" "$target"; then
    # hex: no characters that need quoting in env files or SQL
    echo "$name=$(openssl rand -hex 24)" >> "$target"
    added+=("$name")
  fi
done
chmod 600 "$target"
if [ "$created" = 1 ]; then
  echo "gen-secrets: wrote $target (${#added[@]} passwords, mode 600, values not shown)"
elif [ "${#added[@]}" -gt 0 ]; then
  echo "gen-secrets: appended ${added[*]} to existing $target (existing values untouched, values not shown)"
else
  echo "gen-secrets: $target already has every password, left untouched"
fi
