#!/usr/bin/env bash
# Usage: apply-routing.sh <w100> <w110> <w120> | apply-routing.sh --rollback | apply-routing.sh --show | apply-routing.sh --sync
# After applying, writes Redis `demo:routing` (e.g. "1.0.0=100 1.1.0=0 1.2.0=0") for the control panel.
# --sync republishes the routing nginx is actually running (read from its routing.conf header) to Redis, changes nothing else.
# Renders routing.conf, pushes it into the running nginx container (works with a remote docker context: no bind
# mount), tests it, reloads. Remembers current and previous routing in overlay/.state/routing-<stack> for rollback.
# Env: DC = docker compose command line (set by the Makefile).
set -euo pipefail
: "${DC:?apply-routing.sh: DC (docker compose command line) must be set; run via make}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
state_dir="$here/../.state"; state="$state_dir/routing-${STACK:?apply-routing.sh: STACK must be set (the Makefile exports it)}"
mkdir -p "$state_dir"; printf '*\n' > "$state_dir/.gitignore"

publish_routing() { # publish_routing "<w100> <w110> <w120>"
  local w out; read -r -a w <<<"$1"
  # -x: the value comes from stdin, so quoting never depends on how the docker command is wrapped (limactl shell)
  # shellcheck disable=SC2086
  out="$(printf '%s' "1.0.0=${w[0]} 1.1.0=${w[1]} 1.2.0=${w[2]}" | $DC exec -T redis redis-cli -x SET demo:routing)" \
    || { echo "apply-routing.sh: could not write demo:routing to redis" >&2; return 1; }
  [ "$out" = OK ] || { echo "apply-routing.sh: redis SET demo:routing answered '$out', expected OK" >&2; return 1; }
}

current=""; previous=""
if [ -f "$state" ]; then
  current="$(sed -n 's/^current=//p' "$state")"; previous="$(sed -n 's/^previous=//p' "$state")"
fi

case "${1:-}" in
  --sync)
    # shellcheck disable=SC2086
    header="$($DC exec -T nginx head -n1 /etc/nginx/routing/routing.conf)" \
      || { echo "apply-routing.sh: could not read routing.conf from the nginx container" >&2; exit 1; }
    live="$(printf '%s' "$header" | sed -n 's/^# Generated by render-routing.sh \([0-9]*\) \([0-9]*\) \([0-9]*\) .*/\1 \2 \3/p')"
    [ -n "$live" ] || { echo "apply-routing.sh: cannot read the weights from routing.conf header '$header'" >&2; exit 1; }
    publish_routing "$live"; echo "apply-routing: demo:routing synced to $live"; exit 0;;
  --show) echo "current=${current:-unknown} previous=${previous:-none}"; exit 0;;
  --rollback)
    [ -n "$previous" ] || { echo "apply-routing.sh: no previous routing recorded in $state" >&2; exit 1; }
    set -- $previous;;
esac
new="$1 $2 $3"

# A release that is not running cannot take traffic (nginx would fail to resolve it). 110/120 live in layer `releases`.
# shellcheck disable=SC2086
running="$($DC --profile releases ps --status running --services)" \
  || { echo "apply-routing.sh: could not list running services with '$DC'" >&2; exit 1; }
i=0
for rel in 100 110 120; do
  i=$((i + 1)); eval "w=\${$i}"
  if [ "$w" -gt 0 ] && ! printf '%s\n' "$running" | grep -qx "inventory-api-$rel"; then
    echo "apply-routing.sh: weight $w for inventory-api-$rel but that container is not running." >&2
    echo "  Releases 1.1.0/1.2.0 belong to the layer 'releases': run 'make layer-on L=releases' first." >&2
    exit 1
  fi
done

conf="$("$here/render-routing.sh" "$@")"
# shellcheck disable=SC2086
printf '%s\n' "$conf" | $DC exec -T nginx sh -c 'cat > /etc/nginx/routing/routing.conf.new'
# Test the candidate before it replaces the live file.
# shellcheck disable=SC2086
$DC exec -T nginx sh -c 'cp /etc/nginx/routing/routing.conf /etc/nginx/routing/routing.conf.bak && mv /etc/nginx/routing/routing.conf.new /etc/nginx/routing/routing.conf && { nginx -t || { mv /etc/nginx/routing/routing.conf.bak /etc/nginx/routing/routing.conf; echo "apply-routing: nginx -t failed, previous file restored" >&2; exit 1; }; } && nginx -s reload'
if [ "$new" != "$current" ]; then
  printf 'current=%s\nprevious=%s\n' "$new" "$current" > "$state"
fi
publish_routing "$new"
echo "apply-routing: weights 1.0.0/1.1.0/1.2.0 = $new%"
