#!/usr/bin/env bash
# Usage: render-routing.sh <w100> <w110> <w120>   (integers 0..100 summing to 100; releases 1.0.0 / 1.1.0 / 1.2.0)
# Prints routing.conf on stdout. Fails loudly on bad input.
#
# Method: weighted upstream with a shared-memory zone (smooth weighted round-robin), NOT split_clients.
#   split_clients hashes $request_id: each request has the right probability, but a 100-request sample is
#   binomial (10% can give 6 or 15). A weighted upstream with `zone` keeps its counters in shared memory across
#   worker processes, so any 100 consecutive requests split exactly by the weights. The canary gate needs
#   a minimum number of requests per version, and the deck says "10%" should mean 10 of 100.
# nginx rejects weight=0, so a release with weight 0 is left out of the upstream (it gets no traffic).
set -euo pipefail

if [ "$#" -ne 3 ]; then
  echo "render-routing.sh: expected 3 weights <w100> <w110> <w120>, got $#" >&2; exit 2
fi
sum=0
for w in "$@"; do
  case "$w" in ''|*[!0-9]*) echo "render-routing.sh: weight '$w' is not a non-negative integer" >&2; exit 2;; esac
  [ "$w" -le 100 ] || { echo "render-routing.sh: weight $w is above 100" >&2; exit 2; }
  sum=$((sum + w))
done
[ "$sum" -eq 100 ] || { echo "render-routing.sh: weights $1/$2/$3 sum to $sum, must be 100" >&2; exit 2; }

echo "# Generated by render-routing.sh $1 $2 $3 (inventory-api 1.0.0 / 1.1.0 / 1.2.0). Do not edit by hand."
echo "upstream stock_api {"
echo "    zone stock_api 64k;"
i=0
for rel in 100 110 120; do
  i=$((i + 1)); w="${!i}"
  if [ "$w" -gt 0 ]; then
    echo "    server inventory-api-$rel:8080 weight=$w;"
  fi
done
echo "    keepalive 32;"
echo "}"
