locals {
  # Bootstrap endpoint is returned as SASL_SSL://host:9092; clients want host:port.
  bootstrap = replace(confluent_kafka_cluster.main.bootstrap_endpoint, "SASL_SSL://", "")
  # Flink has Terraform-only credentials; only containers consuming env_file belong here.
  env_file_apps = ["connect", "projector", "storefront", "offers", "demo-control"]

  env_file_lines = concat(
    [
      "# Generated by overlay/terraform/cloud. Contains secrets: keep untracked.",
      "STACK=${var.stack}",
      "KAFKA_BOOTSTRAP=${local.bootstrap}",
      "SR_URL=${data.confluent_schema_registry_cluster.main.rest_endpoint}",
      "CONNECT_GROUP_ID=${var.connect_group_id}",
      "PROJECTOR_GROUP_ID=${var.projector_group_id}",
      "SELLABLE_SINK_GROUP_ID=${var.sellable_sink_group_id}",
      "RESTOCK_SINK_GROUP_ID=${var.restock_sink_group_id}",
      # cost-meter: usage and billed lines of this stack
      "CONFLUENT_ENVIRONMENT_ID=${confluent_environment.main.id}",
      "KAFKA_CLUSTER_ID=${confluent_kafka_cluster.main.id}",
      "FLINK_COMPUTE_POOL_ID=${confluent_flink_compute_pool.main.id}",
    ],
    flatten([
      # "demo-control" becomes DEMO_CONTROL_*
      for app in concat(local.env_file_apps, var.enable_control_center ? ["control-center"] : []) : [
        "${upper(replace(app, "-", "_"))}_KAFKA_API_KEY=${confluent_api_key.kafka[app].id}",
        "${upper(replace(app, "-", "_"))}_KAFKA_API_SECRET=${confluent_api_key.kafka[app].secret}",
        "${upper(replace(app, "-", "_"))}_SR_API_KEY=${confluent_api_key.sr[app].id}",
        "${upper(replace(app, "-", "_"))}_SR_API_SECRET=${confluent_api_key.sr[app].secret}",
      ]
    ]),
    var.enable_dd_streams ? [
      "CONFLUENT_DATADOG_API_KEY=${confluent_api_key.datadog[0].id}",
      "CONFLUENT_DATADOG_API_SECRET=${confluent_api_key.datadog[0].secret}",
    ] : [],
  )
}

output "environment_id" {
  description = "Confluent environment ID."
  value       = confluent_environment.main.id
}

output "kafka_cluster_id" {
  description = "Kafka cluster ID."
  value       = confluent_kafka_cluster.main.id
}

output "kafka_bootstrap" {
  description = "Kafka bootstrap endpoint (host:port)."
  value       = local.bootstrap
}

output "schema_registry_url" {
  description = "Schema Registry REST endpoint."
  value       = data.confluent_schema_registry_cluster.main.rest_endpoint
}

output "flink_compute_pool_id" {
  description = "Flink compute pool ID (for overlay/flink/)."
  value       = confluent_flink_compute_pool.main.id
}

output "flink_rest_endpoint" {
  description = "Flink regional REST endpoint."
  value       = data.confluent_flink_region.main.rest_endpoint
}

output "flink_service_account_id" {
  description = "sa-flink ID, the principal for Flink statements."
  value       = confluent_service_account.app["flink"].id
}

output "flink_api_key" {
  description = "Flink API key ID (secret is in the state only; read it with terraform output -raw flink_api_secret)."
  value       = confluent_api_key.flink.id
}

output "flink_api_secret" {
  description = "Flink API key secret."
  value       = confluent_api_key.flink.secret
  sensitive   = true
}

output "env_file" {
  description = "KEY=VALUE lines for the overlay .env. Sensitive: redirect to a file, never print."
  value       = join("\n", local.env_file_lines)
  sensitive   = true
}

output "datadog_confluent_api_key" {
  description = "Cloud resource management API key ID for the Datadog Confluent Cloud integration (null when enable_dd_streams is false). Feed it to overlay/terraform/datadog as TF_VAR_confluent_api_key."
  value       = var.enable_dd_streams ? confluent_api_key.datadog[0].id : null
  sensitive   = true
}

output "datadog_confluent_api_secret" {
  description = "Secret of datadog_confluent_api_key (null when enable_dd_streams is false). Feed it to overlay/terraform/datadog as TF_VAR_confluent_api_secret."
  value       = var.enable_dd_streams ? confluent_api_key.datadog[0].secret : null
  sensitive   = true
}

output "stack" {
  description = "Stack name."
  value       = var.stack
}

output "schema_check_sr_api_key" {
  description = "Schema Registry key of sa-flink (DeveloperRead on every subject): stack.sh uses it to wait until the Flink input subjects exist. Sensitive."
  value       = confluent_api_key.sr["flink"].id
  sensitive   = true
}

output "schema_check_sr_api_secret" {
  description = "Secret of schema_check_sr_api_key. Sensitive."
  value       = confluent_api_key.sr["flink"].secret
  sensitive   = true
}
