"""Storefront display catalogue (names, prices, colours), independent of the stock API release.

products.json is generated by storefront/scripts/export_products.py and checked in.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

PRODUCTS_FILE = Path(__file__).with_name("products.json")
PRODUCT_IMAGE_DIR = Path(__file__).with_name("product-images")

_cache: list[dict] | None = None


def load_products() -> list[dict]:
    global _cache
    if _cache is None:
        try:
            _cache = json.loads(PRODUCTS_FILE.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise RuntimeError(f"cannot load display catalogue {PRODUCTS_FILE}: {type(exc).__name__}: {exc}") from exc
    return _cache


def get_product(product_id: str) -> dict | None:
    return next((p for p in load_products() if p["product_id"] == product_id), None)


def model_variants(product: dict) -> list[dict]:
    """Every SKU of the product's model (itself included) in display order: colour first, then size."""
    model_id = product.get("model_id")
    if not isinstance(model_id, str):
        raise RuntimeError(f"display catalogue entry {product.get('product_id')} has no model_id; regenerate products.json")
    siblings = sorted((p for p in load_products() if p.get("model_id") == model_id), key=lambda p: p["variant_rank"])
    return [{"product_id": p["product_id"], "colour": p["colour"], "size": p["size"]} for p in siblings]


def product_image_filename(product: dict) -> str | None:
    """Return the approved image asset name for one checked-in catalogue product."""
    name = product.get("name")
    colour = product.get("colour", {}).get("name")
    if not isinstance(name, str) or not isinstance(colour, str):
        return None
    product_type = " ".join(name.split()[:-1])
    if not product_type:
        return None
    slug = lambda value: re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    type_slug, colour_slug = slug(product_type), slug(colour)
    return f"{type_slug}--{colour_slug}.jpg" if type_slug and colour_slug else None


def product_image_path(product_id: str) -> Path | None:
    product = get_product(product_id)
    if product is None:
        return None
    filename = product_image_filename(product)
    if filename is None:
        return None
    candidate = PRODUCT_IMAGE_DIR / filename
    return candidate if candidate.is_file() else None
