"""Storefront display catalogue (names, prices, colours), independent of the stock API release.

products.json is generated by storefront/scripts/export_products.py and checked in.
"""
from __future__ import annotations

import json
from pathlib import Path

PRODUCTS_FILE = Path(__file__).with_name("products.json")

_cache: list[dict] | None = None


def load_products() -> list[dict]:
    global _cache
    if _cache is None:
        try:
            _cache = json.loads(PRODUCTS_FILE.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise RuntimeError(f"cannot load display catalogue {PRODUCTS_FILE}: {type(exc).__name__}: {exc}") from exc
    return _cache


def get_product(product_id: str) -> dict | None:
    return next((p for p in load_products() if p["product_id"] == product_id), None)
